### ISSUE TITLE
MusicBot not updating

### ISSUE THREAD

**Issue by Xaero252** [SuperSandro2000/docker-images#237]
Still on 0.3.4, missing the 0.3.5 and 0.3.6 updates. Using supersandro2000/musicbot:latest. New versions are required due to SoundCloud API changes.

EDIT:

Manually specifying 0.3.6 works, to grab the latest update of the music bot from Github; looking at the dockerhub releases page, it looks like there is a problem with automated version updates on dockerhub. (Both a version 0.3.4 and a version 0 were released approximately 4 hours ago according to that page, while the 0.3.6 version is from several days ago)

**Comment by SuperSandro2000** [comment]
The actual issue is a bit embarrassing but should now be fixed.

**Comment by SuperSandro2000** [comment]
and it should be up and fixed. Please let me know if it is still broken.
