### ISSUE TITLE
MusicBot version outdated

### ISSUE THREAD

**Issue by Kelarik** [SuperSandro2000/docker-images#290]
MusicBot has been updated to 0.3.8, but this docker image statically pulls 0.3.6. Would be convenient if the latest version could be queried, so that manual updates aren't required, or alternatively be able to pass through the desired version as an env variable.

**Comment by SuperSandro2000** [comment]
You should be able to just run ``make update`` in the directory to update the image.

**Comment by SnowDrifterr** [comment]
I'm also having this issue

What do you mean 'run make update'?

**Comment by SuperSandro2000** [comment]
If you clone the repo, go into the directory of the software and run make update you should get the latest version of the software in the Dockerfile. Then you can just build the Dockerfile and have the latest version.
