### ISSUE TITLE
Newest Image in Docker Hub doesn't contain the newest version

### ISSUE THREAD

**Issue by LennartRommeiss** [SuperSandro2000/docker-images#293]
It seems like the newest Docker Image at Docker Hub doesn't contain the latest Musicbot Version.
I saw your commit for the version update, but it seems like this version is not at Docker Hub

https://github.com/SuperSandro2000/docker-images/blob/master/musicbot/Dockerfile

Starting discordmusicbot_Discord-Music-Bot_1 ... done
Attaching to discordmusicbot_Discord-Music-Bot_1
Discord-Music-Bot_1  | [18:48:18] [WARN] [Version]: There is a new version of JMusicBot available!
Discord-Music-Bot_1  | Current version: 0.3.6
Discord-Music-Bot_1  | New Version: 0.3.8
Discord-Music-Bot_1  |
Discord-Music-Bot_1  | Please visit https://github.com/jagrosh/MusicBot/releases/latest to get the latest release.
Discord-Music-Bot_1  | [18:48:18] [INFO] [Startup]: Loaded config from /data/config.txt
Discord-Music-Bot_1  | [18:48:18] [INFO] [JDA]: Login Successful!
Discord-Music-Bot_1  | [18:48:19] [INFO] [WebSocketClient]: Connected to WebSocket
Discord-Music-Bot_1  | [18:48:19] [INFO] [JDA]: Finished Loading!

**Comment by SuperSandro2000** [comment]
Should be fixed with 4cbc307cfdc07d5f7e00daf0d9ce7c7041a2bd29

**Comment by SuperSandro2000** [comment]
Latest version is now up on the registries.
